#!/bin/sh

if [[ ! $(id -u) == 0 ]]; then
    echo "Must be ran as root."
    exit 1
fi

PACKAGE_LIST=(
    alacritty
    bash
    python
    dunst
    feh
    i3-wm
    i3blocks
    irssi
    mpd
    mpv
    ncmpcpp
    neofetch
    newsboat
    neovim-nightly-bin
    picom
    xorg xorg-xinit
    zathura
    zsh
)

printf "Setting up chaotic-aur\n"

if ! grep "chaotic-aur" /etc/pacman.conf >/dev/null; then
    cat <<- EOF
        [chaotic-aur]
        Include = /etc/pacman.d/chaotic-mirrorlist
    EOF
fi

# Need to set up yay

yay -Sy --needed "${PACKAGE_LIST[@]}"
