#!/bin/sh

PACKAGE_LIST=(
    alacritty
    bash
    python
    dunst
    feh
    i3-wm
    i3blocks
    irssi
    mpd
    mpv
    ncmpcpp
    neofetch
    newsboat
    neovim-nightly-bin
    picom
    xorg xorg-xinit
    zathura
    zsh
)

printf "Setting up chaotic-aur"

if ! grep "chaotic" /etc/pacman.conf >/dev/null;
    # shit
fi

yay -Sy --needed "${PACKAGE_LIST[@]}"
