#!/bin/sh

date +'%a %e %b %Y' | awk '{
    day = $1;
    dayofmonth = $2;
    month = $3;
    year = $4;

    length_of_dayofmonth = length(dayofmonth);
    end_of_dayofmonth = substr(dayofmonth, length_of_dayofmonth);

    if (end_of_dayofmonth == "1")
        suffix = "st";
    else if (end_of_dayofmonth == "2")
        suffix = "nd";
    else if (end_of_dayofmonth == "3")
        suffix = "rd";
    else
        suffix = "th";

    if (dayofmonth == "11")
        suffix = "th"
    else if (dayofmonth == "12")
        suffix = "th"
    else if (dayofmonth == "13")
        suffix = "th"

    print day, dayofmonth suffix, month, year
}'
