#!/bin/sh

DAY=$(date +'%e')

date +'%a %e %b %Y' | awk '{
    day = $1;
    dayofmonth = $2;
    month = $3;
    year = $4;

    length_of_dayofmonth = length(dayofmonth);
    end_of_dayofmonth = substr(dayofmonth, length_of_dayofmonth);

    if (end_of_dayofmonth == "1")
        suffix = "st";
    else if (end_of_dayofmonth == "2")
        suffix = "nd";
    else if (end_of_dayofmonth == "3")
        suffix = "rd";
    else
        suffix = "th";

    if (dayofmonth == "11")
        suffix = "th"
    else if (dayofmonth == "12")
        suffix = "th"
    else if (dayofmonth == "13")
        suffix = "th"

    print day, dayofmonth suffix, month, year
}'

case "$BLOCK_BUTTON" in
    1) notify-send "Calendar" "<tt>$(cal --color=never 2>&1 | sed -r 's|'"$DAY"'|<span background="#ffffff" foreground="#000000">'"$DAY"'</span>|g')</tt>" ;;
esac
