#!/bin/sh

get_volume(){
    volume_percentage=$(pactl get-sink-volume "$sink" | awk -F'/' '/Volume/ {gsub(" ","",$2); print $2}')

    printf "%2s\n" "$volume_percentage"
}

toggle_mute_volume(){
    pactl set-sink-mute "$sink" toggle
    if [[ $(pactl get-sink-mute "$sink" | awk '{print $NF}') == "yes" ]]; then
        printf "%s\n" "muted"
    fi
}

volume_up(){
    pactl set-sink-volume "$sink" +${change_interval}%
}

volume_down(){
    pactl set-sink-volume "$sink" -${change_interval}%
}

sink="@DEFAULT_SINK@"
change_interval="5"

case "$BLOCK_BUTTON" in
    1) toggle_mute_volume; get_volume ;;
    4) volume_up; get_volume ;;
    5) volume_down; get_volume ;;
esac

get_volume
