#!/bin/sh

gpu=/sys/devices/pci0000:00/0000:00:03.1/0000:07:00.0

paste -d" " ${gpu}/mem_info_vram_used ${gpu}/mem_info_vram_total \
    | awk '{
        used = $1 / 1024 / 1024;
        total = $2 / 1024 / 1024;
        percentage = $1 / $2 * 100;

        printf "%.0fMB (%.0f%)\n", used, percentage
    }'
